---
title: "Speculative Decoding - The bits and the bytes!"
subtitle: "Why you can not ignore Speculative Decoding: Part-1"
author: "Aakash Kumar Nain ([@A_K_Nain](https://x.com/A_K_Nain))"
date: "2026-04-06"
categories: [LLMs, sepculative decoding, beginner]
image: ""
format:
  html:
    theme: default
    fontsize: 2em
    backgroundcolor: rgb(255, 255, 255);
    code-fold: true
    code-summary: "Show the code"
    css: styles.css
execute: 
  echo: false
---

# Why bother with speculative decoding?

We are in the era of scaling models. Transformers have taken the world by storm, and LLMs are at the forefront. We have not hit any scaling wall, and we continuously see improved capabilities as we scale these models. The definition of a "small model" has changed significantly. While a model with a million parameters was considered small in the past, that label has now shifted to a model with 3-7B parameters.

Like any other approach, scaling also comes with its pros and cons. Ideally, you would want to serve the biggest model with better capabilities at scale. Inference from autoregressive transformers is slow. Decoding `K` tokens takes `K` serial runs of the model. Hence, increasing the size of a model (or the active number of parameters, to be precise) increases latency, which in turn makes the model unusable for many real-world tasks. It makes LLM inference as challenging as, if not more challenging than, LLM training.

There are many ways to mitigate the above problem. In this post, we will discuss one such technique, Speculative Decoding, that does not require any changes to the original model itself, yet can help speed up inference without compromising on the quality of output tokens. We will divide the entirety of speculative decoding into three parts, namely:

- **Speculative Decoding: The bits and the bytes** (this post!) that will give you an overview of the fundamentals of speculative decoding.
- **Medusa and Eagle**: Modern or most common ways to implement speculative decoding.
- **DFlash**: The emerging new cool kid on the block.


# Overview

We will align the notation in our post with the [speculative decoding paper(https://arxiv.org/abs/2211.17192). 
Let $M_p$ be the target model for which we are trying to accelerate inference, and let $p(x_t | x_{<t})$ be the distribution it generates for a prefix $x_{<t}$. Let $M_q$ be a more efficient approximation model for the same task, and let $q(x_t | x_{<t})$ be the distribution it generates for the same prefix. 

The core idea behind speculative decoding is simply this:

1. Use the more efficient (smaller) model to generate $\gamma$ tokens. 
2. Use the target model to verify the generated tokens in parallel.
3. Accept or reject the tokens based on an acceptance criterion (which we will define later in the post).
4. In the best-case scenario, we will accept all the generated tokens. In the worst-case scenario, we will still end up with at least one newly generated token. Consequently, we will end up accepting anywhere from $1$ to $\gamma+1$ tokens in a single forward pass of the target model, hence accelerating inference.




# References